//! Vireo v3.1 — Cross-language conformance test.
//!
//! Reads tests/conformance/vectors/*.json (generated by Python SDK)
//! and asserts that the Rust SDK produces byte-identical:
//!   - canonical wire bytes
//!   - BLAKE2b-256 wire hash
//!   - Ed25519 signature verification
//!
//! North Star: "Prove that Vireo can make independently implemented
//! AI agents interoperable."

use std::fs;
use std::path::PathBuf;

use serde::Deserialize;
use serde_json::Value;
use vireo_ai::{
    canonical_wire_bytes, did_hash, verify_vireo_message, wire_hash, Envelope,
};

#[derive(Debug, Deserialize)]
struct Vector {
    id: String,
    input_fields: InputFields,
    keys: Keys,
    expected_outputs: ExpectedOutputs,
}

#[derive(Debug, Deserialize)]
struct InputFields {
    intent: String,
    timestamp_ms: u64,
    nonce_hex: String,
    sender_did: String,
    recipient_did: String,
    payload: Value,
}

#[derive(Debug, Deserialize)]
struct Keys {
    #[allow(dead_code)]
    private_key_hex: String,
    public_key_hex: String,
}

#[derive(Debug, Deserialize)]
struct ExpectedOutputs {
    canonical_bytes_hex: String,
    canonical_bytes_len: usize,
    wire_hash_hex: String,
    signature_hex: String,
}

fn vectors_dir() -> PathBuf {
    // tests/ → sdk/rust/ → sdk/ → root
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent().unwrap()          // sdk/
        .parent().unwrap()          // root/
        .join("tests/conformance/vectors")
}

fn build_envelope(f: &InputFields) -> Envelope {
    let nonce_bytes = hex::decode(&f.nonce_hex).expect("nonce_hex must be valid hex");
    assert_eq!(nonce_bytes.len(), 16, "nonce must be 16 bytes");
    let mut nonce = [0u8; 16];
    nonce.copy_from_slice(&nonce_bytes);

    Envelope {
        intent: f.intent.clone(),
        timestamp_ms: f.timestamp_ms,
        nonce,
        sender_did_hash: did_hash(&f.sender_did),
        recipient_did_hash: did_hash(&f.recipient_did),
        payload: f.payload.clone(),
    }
}

fn run_vector(path: &PathBuf) {
    let raw = fs::read_to_string(path)
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
    let v: Vector = serde_json::from_str(&raw)
        .unwrap_or_else(|e| panic!("bad JSON in {}: {e}", path.display()));

    println!("\n🌿 {} — {}", v.id, path.file_name().unwrap().to_string_lossy());

    let env = build_envelope(&v.input_fields);
    let canonical = canonical_wire_bytes(&env).expect("canonical_wire_bytes");

    // 1. canonical bytes match
    let canonical_hex = hex::encode(&canonical);
    assert_eq!(
        canonical.len(),
        v.expected_outputs.canonical_bytes_len,
        "canonical length mismatch for {}",
        v.id
    );
    assert_eq!(
        canonical_hex, v.expected_outputs.canonical_bytes_hex,
        "canonical bytes mismatch for {}\n  Python: {}\n  Rust:   {}",
        v.id, v.expected_outputs.canonical_bytes_hex, canonical_hex
    );
    println!("   ✅ canonical bytes match ({} bytes)", canonical.len());

    // 2. wire hash matches
    let h = wire_hash(&canonical);
    let h_hex = hex::encode(h);
    assert_eq!(
        h_hex, v.expected_outputs.wire_hash_hex,
        "wire hash mismatch for {}\n  Python: {}\n  Rust:   {}",
        v.id, v.expected_outputs.wire_hash_hex, h_hex
    );
    println!("   ✅ wire_hash match: {}", h_hex);

    // 3. Python's signature verifies under Rust verifier
    verify_vireo_message(
        &v.keys.public_key_hex,
        &canonical,
        &v.expected_outputs.signature_hex,
    )
    .unwrap_or_else(|e| {
        panic!("Python signature failed Rust verification for {}: {e}", v.id)
    });
    println!("   ✅ Python signature verifies in Rust");

    println!("   🎯 {} — PASS", v.id);
}

#[test]
fn test_all_conformance_vectors() {
    let dir = vectors_dir();
    assert!(dir.exists(), "vectors dir missing: {}", dir.display());

    let mut entries: Vec<_> = fs::read_dir(&dir)
        .expect("read vectors dir")
        .filter_map(|e| e.ok())
        .map(|e| e.path())
        .filter(|p| p.extension().map(|x| x == "json").unwrap_or(false))
        .collect();
    entries.sort();

    assert!(!entries.is_empty(), "no .json vectors found in {}", dir.display());

    for path in &entries {
        run_vector(path);
    }

    println!(
        "\n🌟 North Star: {} vector(s) passed cross-language conformance.",
        entries.len()
    );
}