# ============================================================
# OLLAMA ↔ GEMINI INTEROPERABILITY TESTS
# ============================================================
"""
Interoperability tests between Ollama and Gemini LLM providers.

These tests verify that:
- Both providers implement the same interface
- Messages are consistent across providers
- Contract handling is identical
- Capability discovery works consistently
"""

import pytest
import json
from typing import Dict, Any


class TestOllamaGeminiInterop:
    """Ollama ↔ Gemini interoperability tests."""

    def test_llm_provider_interface(self):
        """MUST: All LLM providers implement the same interface."""
        required_methods = [
            "generate",
            "chat",
            "generate_json",
            "get_model_info"
        ]
        
        # In a real test, this would check actual provider classes
        # For now, verify interface requirements
        for method in required_methods:
            assert isinstance(method, str)

    def test_message_format_consistency(self):
        """MUST: Messages have consistent format across providers."""
        # Message generated by Ollama agent
        ollama_message = {
            "protocol": "VIREO-A2A",
            "version": "2.0.2",
            "message_id": "msg-ollama-001",
            "conversation_id": "conv-test-001",
            "sender": {"id": "ollama-agent", "model": "llama3:8b"},
            "recipient": {"id": "gemini-agent"},
            "intent": "PROPOSE",
            "payload": {
                "task": "Analyze market trends",
                "code": "analysis = analyze(data)"
            },
            "timestamp": 1234567890
        }
        
        # Message generated by Gemini agent
        gemini_message = {
            "protocol": "VIREO-A2A",
            "version": "2.0.2",
            "message_id": "msg-gemini-001",
            "conversation_id": "conv-test-001",
            "sender": {"id": "gemini-agent", "model": "gemini-1.5-pro"},
            "recipient": {"id": "ollama-agent"},
            "intent": "COMMIT",
            "payload": {
                "proposal_id": "msg-ollama-001",
                "contract": {
                    "max_tokens": 1000,
                    "timeout_sec": 30
                }
            },
            "timestamp": 1234567891
        }
        
        # Verify both messages follow the same schema
        for msg in [ollama_message, gemini_message]:
            assert msg["protocol"] == "VIREO-A2A"
            assert msg["version"] == "2.0.2"
            assert "message_id" in msg
            assert "conversation_id" in msg
            assert "sender" in msg
            assert "recipient" in msg
            assert "intent" in msg
            assert "timestamp" in msg

    def test_contract_handling_consistency(self):
        """MUST: Both providers handle contracts correctly."""
        contract = {
            "max_tokens": 500,
            "timeout_sec": 30,
            "verify_timeout_sec": 15,
            "max_rounds": 3,
            "verify": "result.accuracy > 0.9"
        }
        
        # Verify contract structure is consistent
        assert contract["max_tokens"] == 500
        assert contract["timeout_sec"] == 30
        assert contract["verify_timeout_sec"] == 15
        assert contract["max_rounds"] == 3
        assert "verify" in contract
        
        # Both providers should handle contract validation identically
        is_valid = self._validate_contract(contract)
        assert is_valid is True
        
        # Invalid contract should be rejected by both
        invalid_contract = {"max_tokens": -1}
        is_valid = self._validate_contract(invalid_contract)
        assert is_valid is False
    
    def _validate_contract(self, contract: Dict) -> bool:
        """Validate contract (same logic for both providers)."""
        if contract.get("max_tokens", 0) < 0:
            return False
        if contract.get("timeout_sec", 0) < 0:
            return False
        if contract.get("verify_timeout_sec", 0) < 0:
            return False
        if contract.get("max_rounds", 0) < 0:
            return False
        return True

    def test_capability_discovery(self):
        """MUST: Capability discovery works consistently."""
        # Ollama agent capabilities
        ollama_capabilities = ["chat", "code_generation", "analysis"]
        
        # Gemini agent capabilities
        gemini_capabilities = ["chat", "reasoning", "data_analysis"]
        
        # Both agents should be able to discover capabilities
        assert "chat" in ollama_capabilities
        assert "chat" in gemini_capabilities
        
        # Capability discovery should use same format
        discovery_message = {
            "intent": "QUERY_CAPABILITIES",
            "payload": {}
        }
        
        response_format = {
            "intent": "INFORM_CAPABILITIES",
            "payload": {
                "capabilities": ["chat", "reasoning"]
            }
        }
        
        assert discovery_message["intent"] == "QUERY_CAPABILITIES"
        assert "capabilities" in response_format["payload"]

    def test_negotiation_consistency(self):
        """SHOULD: Negotiation flow is consistent across providers."""
        # Propose from Ollama
        propose = {
            "intent": "PROPOSE",
            "payload": {
                "task": "Analyze data",
                "contract": {"max_tokens": 500}
            }
        }
        
        # Commit from Gemini
        commit = {
            "intent": "COMMIT",
            "payload": {
                "proposal_id": "msg-001",
                "contract": {"max_tokens": 500}
            }
        }
        
        # Both providers should follow the same flow
        assert propose["intent"] == "PROPOSE"
        assert commit["intent"] == "COMMIT"
        
        # Contract should be preserved
        assert propose["payload"]["contract"]["max_tokens"] == 500
        assert commit["payload"]["contract"]["max_tokens"] == 500

    def test_verification_consistency(self):
        """SHOULD: Verification is consistent across providers."""
        # Ollama verification
        ollama_verify = {
            "intent": "VERIFY",
            "payload": {
                "proposal_id": "msg-001",
                "result": {"accuracy": 0.95}
            }
        }
        
        # Gemini verification
        gemini_verify = {
            "intent": "VERIFY",
            "payload": {
                "proposal_id": "msg-001",
                "result": {"accuracy": 0.95}
            }
        }
        
        # Both providers should use the same format
        assert ollama_verify["intent"] == "VERIFY"
        assert gemini_verify["intent"] == "VERIFY"
        assert ollama_verify["payload"]["result"]["accuracy"] == 0.95
        assert gemini_verify["payload"]["result"]["accuracy"] == 0.95

    def test_timeout_handling(self):
        """SHOULD: Timeout handling is consistent."""
        timeout_sec = 30
        
        # Both providers should respect timeout
        assert timeout_sec > 0
        assert isinstance(timeout_sec, int)
        
        # Contract should include timeout
        contract = {"timeout_sec": timeout_sec}
        assert contract["timeout_sec"] == 30

    def test_error_handling(self):
        """SHOULD: Error handling is consistent."""
        # Both providers should use same error format
        error_response = {
            "status": "error",
            "error": {
                "code": "CONTRACT_VIOLATION",
                "message": "Token limit exceeded",
                "details": {"max_tokens": 500, "attempted": 600}
            }
        }
        
        assert error_response["status"] == "error"
        assert "code" in error_response["error"]
        assert "message" in error_response["error"]
        assert error_response["error"]["code"] == "CONTRACT_VIOLATION"